In [2]:
import numpy as np

In [3]:
#Criação de um array 2D
arr = [[1,2,3],[4,5,6]]
array = np.array(arr)
array.shape

(2, 3)

In [5]:
#Arrays contendo apenas zeros e ums
size = (3,3)
array_zeros = np.zeros(size)
print(array_zeros)

array_ums = np.ones(size)
print(array_ums)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


np.linspace = Usado para criar intervalos de dados linearmente espaçados
Isto é, que possuem um ponto inicial e final, e uma quantidade de valores a serem preenchidos
Todos os valores terão a mesma distância entre si, de acordo com a quantidade de elementos definida

In [13]:
#Cria 5 valores entre 0 e 10, com espaçamento igual entre eles
lin = np.linspace(0, 10, 5)
lin

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
np.linspace(-1, 1, 100)

array([-1.        , -0.97979798, -0.95959596, -0.93939394, -0.91919192,
       -0.8989899 , -0.87878788, -0.85858586, -0.83838384, -0.81818182,
       -0.7979798 , -0.77777778, -0.75757576, -0.73737374, -0.71717172,
       -0.6969697 , -0.67676768, -0.65656566, -0.63636364, -0.61616162,
       -0.5959596 , -0.57575758, -0.55555556, -0.53535354, -0.51515152,
       -0.49494949, -0.47474747, -0.45454545, -0.43434343, -0.41414141,
       -0.39393939, -0.37373737, -0.35353535, -0.33333333, -0.31313131,
       -0.29292929, -0.27272727, -0.25252525, -0.23232323, -0.21212121,
       -0.19191919, -0.17171717, -0.15151515, -0.13131313, -0.11111111,
       -0.09090909, -0.07070707, -0.05050505, -0.03030303, -0.01010101,
        0.01010101,  0.03030303,  0.05050505,  0.07070707,  0.09090909,
        0.11111111,  0.13131313,  0.15151515,  0.17171717,  0.19191919,
        0.21212121,  0.23232323,  0.25252525,  0.27272727,  0.29292929,
        0.31313131,  0.33333333,  0.35353535,  0.37373737,  0.39

Matriz identidade

In [16]:
n=4
x = np.eye(n)
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#Criação de valores aleatórios
x = np.random.random(size = (2,3)) # gera valores aleatórios entre 0 e 1
print(x, "\n")

x = np.random.randint(1,200, size = (3,4))
print(x)

[[0.59724396 0.67053051 0.94578172]
 [0.50756693 0.0525032  0.93908322]] 

[[ 27   4 173   5]
 [ 85 118 178  87]
 [189  95   9  55]]


Indexação de arrays

Arrays podem ser dimensionais ou bidimensionais

arrays dimensionais = np.array(size = 4)
arrays bidimensionais = np.array(size = (1,4))

In [27]:
#Acessando o último elemento de um array unidimensional
a = np.array(np.random.randint(1,100,size=4))
print(a)
print(a[-1])

[49 61  2 28]
28


In [29]:
#Acessando mais de um elemento em um array
#O segundo elemento é exclusivo, não entra na indexação
a[0:2]

array([49, 61])

In [ ]:
#Acessando elementos em um array 2D
# B[i:k, j:i]
# #O slicing incluirá até k-1 e i-1 respectivamente 
arr = np.array(np.random.randint(1,100, size=(4,4)))
print(arr)



arr[1:3, 1:3]

[[ 8 51 20 36]
 [61  2 51 59]
 [74 63 91 76]
 [11 98 25 22]]


array([[ 2, 51],
       [63, 91]])

Slicing

In [3]:
x = np.linspace(start=10, stop=100, num=10)
print(x, "\n", x.shape)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.] 
 (10,)


In [4]:
x_novo = np.linspace(0, 6, 100).reshape(-1, 1)  # gera valores de 0 a 6
x_novo

array([[0.        ],
       [0.06060606],
       [0.12121212],
       [0.18181818],
       [0.24242424],
       [0.3030303 ],
       [0.36363636],
       [0.42424242],
       [0.48484848],
       [0.54545455],
       [0.60606061],
       [0.66666667],
       [0.72727273],
       [0.78787879],
       [0.84848485],
       [0.90909091],
       [0.96969697],
       [1.03030303],
       [1.09090909],
       [1.15151515],
       [1.21212121],
       [1.27272727],
       [1.33333333],
       [1.39393939],
       [1.45454545],
       [1.51515152],
       [1.57575758],
       [1.63636364],
       [1.6969697 ],
       [1.75757576],
       [1.81818182],
       [1.87878788],
       [1.93939394],
       [2.        ],
       [2.06060606],
       [2.12121212],
       [2.18181818],
       [2.24242424],
       [2.3030303 ],
       [2.36363636],
       [2.42424242],
       [2.48484848],
       [2.54545455],
       [2.60606061],
       [2.66666667],
       [2.72727273],
       [2.78787879],
       [2.848

In [4]:
#Slicing em arrays 2D (matrizes)
x = x.reshape(2,5)
print(x)

[[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]


In [7]:
#Slicing extração de sub arrays bidimensionais
print("primeira linha inteira: ", x[0, :])
print("primeira linha, segunda a quarta coluna", x[0, 1:4])
print("última coluna inteira: ", x[:, [-1]])

primeira linha inteira:  [10. 20. 30. 40. 50.]
primeira linha, segunda a quarta coluna [20. 30. 40.]
última coluna inteira:  [[ 50.]
 [100.]]
