In [1]:
import numpy as np

Comparações
-operações elemento a elemento
Saber se um array ou valor é maior, menor, ou igual a outro valor ou array

In [4]:
a = np.array([1,2,3])
b = np.array([2,0,2])
s = 3

print("comparação maior:")
print(a>b)
print(a>s)

print("comparação menor:")
print(a<b)
print(a<s)

print("comparação igual:")
print(a==b)
print(a==b)

comparação maior:
[False  True  True]
[False False False]
comparação menor:
[ True False False]
[ True  True False]
comparação igual:
[False False False]
[False False False]


Indexação booleana
filtro para verificar valores que satisfazem uma certa condição

In [ ]:
#Cria um array booleano onde os valores de A são menor ou igual o 2
cond = a<=2

#cria um array para receber a, mas somente com os valores da condição cond
d = a[cond]
d

array([1, 2])

Indexação booleana
Realizar uma operação de filtro e retornar em um subarray contendo uma cópia dos elementos somente onde a condição de filtro se aplica

In [8]:
x = np.array([[1,2],[3,4]])
y = np.array([1.5, 3.5])

print("x: \n", x)
print("y: \n",y)

x: 
 [[1 2]
 [3 4]]
y: 
 [1.5 3.5]


In [13]:
x = np.array(np.random.randint(1,50, size = (3,3)))
x

array([[16, 26, 43],
       [ 1,  9, 46],
       [47,  6, 24]])

In [24]:
#Indexação booleana
#retornar o número de elementos maiores que k

k=10
cond = x>k
print(cond,"\n")

arr = x[cond]
print("Elementos maiores que 10 do array: \n",arr,"\n")

print(f"número de elementos maiores que {k}: ", len(arr),"\n")

x_pares = cond = x%2==0
print(x_pares,"\n")

pares = x[x_pares]
print("números pares: ",pares,"\n")

print("quantidade de números pares:",len(pares))


[[ True  True  True]
 [False False  True]
 [ True False  True]] 

Elementos maiores que 10 do array: 
 [16 26 43 46 47 24] 

número de elementos maiores que 10:  6 

[[ True  True False]
 [False False  True]
 [False  True  True]] 

números pares:  [16 26 46  6 24] 

quantidade de números pares: 5
