In [8]:
import numpy as np

In [9]:
#Transformando uma matriz em um vetor coluna
#reshape(l,c)
#Os números do reshape tem que ser compatível com o produto das dimensões do array original
#Um array de 9 elementos, teria quer ter um reshape 9,1 ou 1,9

arr = np.array(np.random.randint(1,30, size = (3,3)))
print(arr)

print("transformação de um vetor em coluna: \n", arr.reshape(9,1))

[[13 13  2]
 [ 2  3  2]
 [18  6 24]]
transformação de um vetor em coluna: 
 [[13]
 [13]
 [ 2]
 [ 2]
 [ 3]
 [ 2]
 [18]
 [ 6]
 [24]]


Transposição de matriz
O que é linha vira coluna, o que é coluna vira linha

In [11]:
print("Matriz transposta: \n", arr.T)

Matriz transposta: 
 [[13  2 18]
 [13  3  6]
 [ 2  2 24]]


In [14]:
#Somar os elementos da matriz ao longo de um determinado eixo, ou todos os elementos do arrya
#linhas -> axis = 0
#colunas -> axis = 1
print("soma de todos os elementos do array: ",arr.sum())
print("soma do array ao longo das linhas", np.sum(arr, axis=0))
print("soma do arraya o longo das colunas: ", np.sum(arr, axis = 1))

soma de todos os elementos do array:  83
soma do array ao longo das linhas [33 22 28]
soma do arraya o longo das colunas:  [28  7 48]


In [20]:
#Tirar a média das linhas e colunas
#np.mean -> média em um dado eixo, axis = {0: linha, 1:coluna}
print(arr)

print("médis de todos os elementos do array: ", arr.mean())
print("médias do eixo x: ", np.mean(arr, axis = 0))
print("médias do eixo y: ", np.mean(arr, axis = 1))

[[13 13  2]
 [ 2  3  2]
 [18  6 24]]
médis de todos os elementos do array:  9.222222222222221
médias do eixo x:  [11.          7.33333333  9.33333333]
médias do eixo y:  [ 9.33333333  2.33333333 16.        ]


In [24]:
#np.where
#Identificação dos índices onde uma dada condição booleana é atendida. Uso conjunto com indexação booleana
cond = arr % 2 ==0
print(np.where(cond))

(array([0, 1, 1, 2, 2, 2], dtype=int64), array([2, 0, 2, 0, 1, 2], dtype=int64))
