In [1]:
import numpy as np

In [5]:
u = np.array([1,0])
v = np.array([0,1])

#x = u+v
x = np.add(u,v)
x

array([1, 1])

Broadcasting

Quando precisamos fazer operações matriciais com arrays e elementos que não estão exatamente na mesma estrutura do array

ex:

import numpy as np

a = np.array([1, 2, 3])
b = 2

result = a + b
print(result)

[3 4 5]

O python replica os dados para serem percorridos por todo o array

In [7]:
#Operações aritméticas com arrays

x = np.ones((2,2))
y = np.eye(2)


print(x)
print(y)

[[1. 1.]
 [1. 1.]]
[[1. 0.]
 [0. 1.]]


In [11]:
#Soma
print("x +y: \n", x+y)

print("soma com float / int: \n", x+2)

x +y: 
 [[2. 1.]
 [1. 2.]]
soma com float / int: 
 [[3. 3.]
 [3. 3.]]


In [12]:
#Subtração
print("subtração de 2 arrays: \n", x-y)
print("subtração de x por 2: \n", x-2) # broadcasting

subtração de 2 arrays: 
 [[0. 1.]
 [1. 0.]]
subtração de x por 2: 
 [[-1. -1.]
 [-1. -1.]]


In [13]:
#divisão
print("divisão de 2 arrays: \n", x/y)
print("divisão de x por 2: \n", x/2) # broadcasting

divisão de 2 arrays: 
 [[ 1. inf]
 [inf  1.]]
divisão de x por 2: 
 [[0.5 0.5]
 [0.5 0.5]]


C:\Users\jpkun\AppData\Local\Temp\ipykernel_17588\4175621888.py:2: RuntimeWarning: divide by zero encountered in divide
  print("divisão de 2 arrays: \n", x/y)


In [14]:
#Quando o broadcasting não funciona
np.array([1,2,3])+ np.array([1,2])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [18]:
#Multiplicação
print(x)
print("multiplicação de x por y: \n", x*y)
print("multiplicação de x por 2: \n", x*2)

[[1. 1.]
 [1. 1.]]
multiplicação de x por y: 
 [[1. 0.]
 [0. 1.]]
multiplicação de x por 2: 
 [[2. 2.]
 [2. 2.]]


In [20]:
#Multiplicação matricial
print("x: \n",x, "\n")
print("y: \n",y,"\n")


print("multiplicação matricial (np.dot): \n", np.dot(x,y))

x: 
 [[1. 1.]
 [1. 1.]] 

y: 
 [[1. 0.]
 [0. 1.]] 

multiplicação matricial (np.dot): 
 [[1. 1.]
 [1. 1.]]
